// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AbyssActivity : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static AbyssActivity GetRootAsAbyssActivity(ByteBuffer _bb) { return GetRootAsAbyssActivity(_bb, new AbyssActivity()); }
  public static AbyssActivity GetRootAsAbyssActivity(ByteBuffer _bb, AbyssActivity obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AbyssActivity __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ActivityId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int DangoList(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int DangoListLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetDangoListBytes() { return __p.__vector_as_span<int>(6, 4); }
#else
  public ArraySegment<byte>? GetDangoListBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public int[] GetDangoListArray() { return __p.__vector_as_array<int>(6); }
  public int ShopId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MarkId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string SceneActor { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSceneActorBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetSceneActorBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetSceneActorArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<WWParser.Defs.AbyssActivity> CreateAbyssActivity(FlatBufferBuilder builder,
      int activity_id = 0,
      VectorOffset dango_listOffset = default(VectorOffset),
      int shop_id = 0,
      int mark_id = 0,
      StringOffset scene_actorOffset = default(StringOffset)) {
    builder.StartTable(5);
    AbyssActivity.AddSceneActor(builder, scene_actorOffset);
    AbyssActivity.AddMarkId(builder, mark_id);
    AbyssActivity.AddShopId(builder, shop_id);
    AbyssActivity.AddDangoList(builder, dango_listOffset);
    AbyssActivity.AddActivityId(builder, activity_id);
    return AbyssActivity.EndAbyssActivity(builder);
  }

  public static void StartAbyssActivity(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddActivityId(FlatBufferBuilder builder, int activityId) { builder.AddInt(0, activityId, 0); }
  public static void AddDangoList(FlatBufferBuilder builder, VectorOffset dangoListOffset) { builder.AddOffset(1, dangoListOffset.Value, 0); }
  public static VectorOffset CreateDangoListVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDangoListVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDangoListVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDangoListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDangoListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddShopId(FlatBufferBuilder builder, int shopId) { builder.AddInt(2, shopId, 0); }
  public static void AddMarkId(FlatBufferBuilder builder, int markId) { builder.AddInt(3, markId, 0); }
  public static void AddSceneActor(FlatBufferBuilder builder, StringOffset sceneActorOffset) { builder.AddOffset(4, sceneActorOffset.Value, 0); }
  public static Offset<WWParser.Defs.AbyssActivity> EndAbyssActivity(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.AbyssActivity>(o);
  }
  public AbyssActivityT UnPack() {
    var _o = new AbyssActivityT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(AbyssActivityT _o) {
    _o.ActivityId = this.ActivityId;
    _o.DangoList = new List<int>();
    for (var _j = 0; _j < this.DangoListLength; ++_j) {_o.DangoList.Add(this.DangoList(_j));}
    _o.ShopId = this.ShopId;
    _o.MarkId = this.MarkId;
    _o.SceneActor = this.SceneActor;
  }
  public static Offset<WWParser.Defs.AbyssActivity> Pack(FlatBufferBuilder builder, AbyssActivityT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.AbyssActivity>);
    var _dango_list = default(VectorOffset);
    if (_o.DangoList != null) {
      var __dango_list = _o.DangoList.ToArray();
      _dango_list = CreateDangoListVector(builder, __dango_list);
    }
    var _scene_actor = _o.SceneActor == null ? default(StringOffset) : builder.CreateString(_o.SceneActor);
    return CreateAbyssActivity(
      builder,
      _o.ActivityId,
      _dango_list,
      _o.ShopId,
      _o.MarkId,
      _scene_actor);
  }
}

public class AbyssActivityT
{
  [Newtonsoft.Json.JsonProperty("activity_id")]
  public int ActivityId { get; set; }
  [Newtonsoft.Json.JsonProperty("dango_list")]
  public List<int> DangoList { get; set; }
  [Newtonsoft.Json.JsonProperty("shop_id")]
  public int ShopId { get; set; }
  [Newtonsoft.Json.JsonProperty("mark_id")]
  public int MarkId { get; set; }
  [Newtonsoft.Json.JsonProperty("scene_actor")]
  public string SceneActor { get; set; }

  public AbyssActivityT() {
    this.ActivityId = 0;
    this.DangoList = null;
    this.ShopId = 0;
    this.MarkId = 0;
    this.SceneActor = null;
  }
}


static public class AbyssActivityVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ActivityId*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*DangoList*/, 4 /*int*/, false)
      && verifier.VerifyField(tablePos, 8 /*ShopId*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*MarkId*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 12 /*SceneActor*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
