// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AdventureTaskChapter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static AdventureTaskChapter GetRootAsAdventureTaskChapter(ByteBuffer _bb) { return GetRootAsAdventureTaskChapter(_bb, new AdventureTaskChapter()); }
  public static AdventureTaskChapter GetRootAsAdventureTaskChapter(ByteBuffer _bb, AdventureTaskChapter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AdventureTaskChapter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public int DropIds { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<WWParser.Defs.AdventureTaskChapter> CreateAdventureTaskChapter(FlatBufferBuilder builder,
      int id = 0,
      StringOffset nameOffset = default(StringOffset),
      int drop_ids = 0) {
    builder.StartTable(3);
    AdventureTaskChapter.AddDropIds(builder, drop_ids);
    AdventureTaskChapter.AddName(builder, nameOffset);
    AdventureTaskChapter.AddId(builder, id);
    return AdventureTaskChapter.EndAdventureTaskChapter(builder);
  }

  public static void StartAdventureTaskChapter(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddDropIds(FlatBufferBuilder builder, int dropIds) { builder.AddInt(2, dropIds, 0); }
  public static Offset<WWParser.Defs.AdventureTaskChapter> EndAdventureTaskChapter(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.AdventureTaskChapter>(o);
  }
  public AdventureTaskChapterT UnPack() {
    var _o = new AdventureTaskChapterT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(AdventureTaskChapterT _o) {
    _o.Id = this.Id;
    _o.Name = this.Name;
    _o.DropIds = this.DropIds;
  }
  public static Offset<WWParser.Defs.AdventureTaskChapter> Pack(FlatBufferBuilder builder, AdventureTaskChapterT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.AdventureTaskChapter>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    return CreateAdventureTaskChapter(
      builder,
      _o.Id,
      _name,
      _o.DropIds);
  }
}

public class AdventureTaskChapterT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("name")]
  public string Name { get; set; }
  [Newtonsoft.Json.JsonProperty("drop_ids")]
  public int DropIds { get; set; }

  public AdventureTaskChapterT() {
    this.Id = 0;
    this.Name = null;
    this.DropIds = 0;
  }
}


static public class AdventureTaskChapterVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyField(tablePos, 8 /*DropIds*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
