// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AreaAtmosphereInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static AreaAtmosphereInfo GetRootAsAreaAtmosphereInfo(ByteBuffer _bb) { return GetRootAsAreaAtmosphereInfo(_bb, new AreaAtmosphereInfo()); }
  public static AreaAtmosphereInfo GetRootAsAreaAtmosphereInfo(ByteBuffer _bb, AreaAtmosphereInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AreaAtmosphereInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string DaPath { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDaPathBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDaPathBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDaPathArray() { return __p.__vector_as_array<byte>(6); }
  public bool IsTod { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public int Priority { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int FadeTime { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)3; } }

  public static Offset<WWParser.Defs.AreaAtmosphereInfo> CreateAreaAtmosphereInfo(FlatBufferBuilder builder,
      int id = 0,
      StringOffset da_pathOffset = default(StringOffset),
      bool is_tod = false,
      int priority = 0,
      int fade_time = 3) {
    builder.StartTable(5);
    AreaAtmosphereInfo.AddFadeTime(builder, fade_time);
    AreaAtmosphereInfo.AddPriority(builder, priority);
    AreaAtmosphereInfo.AddDaPath(builder, da_pathOffset);
    AreaAtmosphereInfo.AddId(builder, id);
    AreaAtmosphereInfo.AddIsTod(builder, is_tod);
    return AreaAtmosphereInfo.EndAreaAtmosphereInfo(builder);
  }

  public static void StartAreaAtmosphereInfo(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddDaPath(FlatBufferBuilder builder, StringOffset daPathOffset) { builder.AddOffset(1, daPathOffset.Value, 0); }
  public static void AddIsTod(FlatBufferBuilder builder, bool isTod) { builder.AddBool(2, isTod, false); }
  public static void AddPriority(FlatBufferBuilder builder, int priority) { builder.AddInt(3, priority, 0); }
  public static void AddFadeTime(FlatBufferBuilder builder, int fadeTime) { builder.AddInt(4, fadeTime, 3); }
  public static Offset<WWParser.Defs.AreaAtmosphereInfo> EndAreaAtmosphereInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.AreaAtmosphereInfo>(o);
  }
  public AreaAtmosphereInfoT UnPack() {
    var _o = new AreaAtmosphereInfoT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(AreaAtmosphereInfoT _o) {
    _o.Id = this.Id;
    _o.DaPath = this.DaPath;
    _o.IsTod = this.IsTod;
    _o.Priority = this.Priority;
    _o.FadeTime = this.FadeTime;
  }
  public static Offset<WWParser.Defs.AreaAtmosphereInfo> Pack(FlatBufferBuilder builder, AreaAtmosphereInfoT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.AreaAtmosphereInfo>);
    var _da_path = _o.DaPath == null ? default(StringOffset) : builder.CreateString(_o.DaPath);
    return CreateAreaAtmosphereInfo(
      builder,
      _o.Id,
      _da_path,
      _o.IsTod,
      _o.Priority,
      _o.FadeTime);
  }
}

public class AreaAtmosphereInfoT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("da_path")]
  public string DaPath { get; set; }
  [Newtonsoft.Json.JsonProperty("is_tod")]
  public bool IsTod { get; set; }
  [Newtonsoft.Json.JsonProperty("priority")]
  public int Priority { get; set; }
  [Newtonsoft.Json.JsonProperty("fade_time")]
  public int FadeTime { get; set; }

  public AreaAtmosphereInfoT() {
    this.Id = 0;
    this.DaPath = null;
    this.IsTod = false;
    this.Priority = 0;
    this.FadeTime = 3;
  }
}


static public class AreaAtmosphereInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*DaPath*/, false)
      && verifier.VerifyField(tablePos, 8 /*IsTod*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 10 /*Priority*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*FadeTime*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
