// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct BabelTowerActivity : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static BabelTowerActivity GetRootAsBabelTowerActivity(ByteBuffer _bb) { return GetRootAsBabelTowerActivity(_bb, new BabelTowerActivity()); }
  public static BabelTowerActivity GetRootAsBabelTowerActivity(ByteBuffer _bb, BabelTowerActivity obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BabelTowerActivity __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ActivityId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int ItemId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int ShareId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<WWParser.Defs.BabelTowerActivity> CreateBabelTowerActivity(FlatBufferBuilder builder,
      int activity_id = 0,
      int item_id = 0,
      int share_id = 0) {
    builder.StartTable(3);
    BabelTowerActivity.AddShareId(builder, share_id);
    BabelTowerActivity.AddItemId(builder, item_id);
    BabelTowerActivity.AddActivityId(builder, activity_id);
    return BabelTowerActivity.EndBabelTowerActivity(builder);
  }

  public static void StartBabelTowerActivity(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddActivityId(FlatBufferBuilder builder, int activityId) { builder.AddInt(0, activityId, 0); }
  public static void AddItemId(FlatBufferBuilder builder, int itemId) { builder.AddInt(1, itemId, 0); }
  public static void AddShareId(FlatBufferBuilder builder, int shareId) { builder.AddInt(2, shareId, 0); }
  public static Offset<WWParser.Defs.BabelTowerActivity> EndBabelTowerActivity(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.BabelTowerActivity>(o);
  }
  public BabelTowerActivityT UnPack() {
    var _o = new BabelTowerActivityT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(BabelTowerActivityT _o) {
    _o.ActivityId = this.ActivityId;
    _o.ItemId = this.ItemId;
    _o.ShareId = this.ShareId;
  }
  public static Offset<WWParser.Defs.BabelTowerActivity> Pack(FlatBufferBuilder builder, BabelTowerActivityT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.BabelTowerActivity>);
    return CreateBabelTowerActivity(
      builder,
      _o.ActivityId,
      _o.ItemId,
      _o.ShareId);
  }
}

public class BabelTowerActivityT
{
  [Newtonsoft.Json.JsonProperty("activity_id")]
  public int ActivityId { get; set; }
  [Newtonsoft.Json.JsonProperty("item_id")]
  public int ItemId { get; set; }
  [Newtonsoft.Json.JsonProperty("share_id")]
  public int ShareId { get; set; }

  public BabelTowerActivityT() {
    this.ActivityId = 0;
    this.ItemId = 0;
    this.ShareId = 0;
  }
}


static public class BabelTowerActivityVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ActivityId*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*ItemId*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*ShareId*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
