// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Character : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Character GetRootAsCharacter(ByteBuffer _bb) { return GetRootAsCharacter(_bb, new Character()); }
  public static Character GetRootAsCharacter(ByteBuffer _bb, Character obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Character __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public string ScoreName { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetScoreNameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetScoreNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetScoreNameArray() { return __p.__vector_as_array<byte>(8); }
  public string Color { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetColorBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetColorBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetColorArray() { return __p.__vector_as_array<byte>(10); }
  public string BarSprite { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBarSpriteBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetBarSpriteBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetBarSpriteArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<WWParser.Defs.Character> CreateCharacter(FlatBufferBuilder builder,
      int id = 0,
      StringOffset nameOffset = default(StringOffset),
      StringOffset score_nameOffset = default(StringOffset),
      StringOffset colorOffset = default(StringOffset),
      StringOffset bar_spriteOffset = default(StringOffset)) {
    builder.StartTable(5);
    Character.AddBarSprite(builder, bar_spriteOffset);
    Character.AddColor(builder, colorOffset);
    Character.AddScoreName(builder, score_nameOffset);
    Character.AddName(builder, nameOffset);
    Character.AddId(builder, id);
    return Character.EndCharacter(builder);
  }

  public static void StartCharacter(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddScoreName(FlatBufferBuilder builder, StringOffset scoreNameOffset) { builder.AddOffset(2, scoreNameOffset.Value, 0); }
  public static void AddColor(FlatBufferBuilder builder, StringOffset colorOffset) { builder.AddOffset(3, colorOffset.Value, 0); }
  public static void AddBarSprite(FlatBufferBuilder builder, StringOffset barSpriteOffset) { builder.AddOffset(4, barSpriteOffset.Value, 0); }
  public static Offset<WWParser.Defs.Character> EndCharacter(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.Character>(o);
  }
  public CharacterT UnPack() {
    var _o = new CharacterT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CharacterT _o) {
    _o.Id = this.Id;
    _o.Name = this.Name;
    _o.ScoreName = this.ScoreName;
    _o.Color = this.Color;
    _o.BarSprite = this.BarSprite;
  }
  public static Offset<WWParser.Defs.Character> Pack(FlatBufferBuilder builder, CharacterT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.Character>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    var _score_name = _o.ScoreName == null ? default(StringOffset) : builder.CreateString(_o.ScoreName);
    var _color = _o.Color == null ? default(StringOffset) : builder.CreateString(_o.Color);
    var _bar_sprite = _o.BarSprite == null ? default(StringOffset) : builder.CreateString(_o.BarSprite);
    return CreateCharacter(
      builder,
      _o.Id,
      _name,
      _score_name,
      _color,
      _bar_sprite);
  }
}

public class CharacterT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("name")]
  public string Name { get; set; }
  [Newtonsoft.Json.JsonProperty("score_name")]
  public string ScoreName { get; set; }
  [Newtonsoft.Json.JsonProperty("color")]
  public string Color { get; set; }
  [Newtonsoft.Json.JsonProperty("bar_sprite")]
  public string BarSprite { get; set; }

  public CharacterT() {
    this.Id = 0;
    this.Name = null;
    this.ScoreName = null;
    this.Color = null;
    this.BarSprite = null;
  }
}


static public class CharacterVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyString(tablePos, 8 /*ScoreName*/, false)
      && verifier.VerifyString(tablePos, 10 /*Color*/, false)
      && verifier.VerifyString(tablePos, 12 /*BarSprite*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
