// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ClueEntrance : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ClueEntrance GetRootAsClueEntrance(ByteBuffer _bb) { return GetRootAsClueEntrance(_bb, new ClueEntrance()); }
  public static ClueEntrance GetRootAsClueEntrance(ByteBuffer _bb, ClueEntrance obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClueEntrance __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int ContentGroupId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Title { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTitleBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetTitleBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetTitleArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<WWParser.Defs.ClueEntrance> CreateClueEntrance(FlatBufferBuilder builder,
      int id = 0,
      int content_group_id = 0,
      StringOffset titleOffset = default(StringOffset)) {
    builder.StartTable(3);
    ClueEntrance.AddTitle(builder, titleOffset);
    ClueEntrance.AddContentGroupId(builder, content_group_id);
    ClueEntrance.AddId(builder, id);
    return ClueEntrance.EndClueEntrance(builder);
  }

  public static void StartClueEntrance(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddContentGroupId(FlatBufferBuilder builder, int contentGroupId) { builder.AddInt(1, contentGroupId, 0); }
  public static void AddTitle(FlatBufferBuilder builder, StringOffset titleOffset) { builder.AddOffset(2, titleOffset.Value, 0); }
  public static Offset<WWParser.Defs.ClueEntrance> EndClueEntrance(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.ClueEntrance>(o);
  }
  public ClueEntranceT UnPack() {
    var _o = new ClueEntranceT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ClueEntranceT _o) {
    _o.Id = this.Id;
    _o.ContentGroupId = this.ContentGroupId;
    _o.Title = this.Title;
  }
  public static Offset<WWParser.Defs.ClueEntrance> Pack(FlatBufferBuilder builder, ClueEntranceT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.ClueEntrance>);
    var _title = _o.Title == null ? default(StringOffset) : builder.CreateString(_o.Title);
    return CreateClueEntrance(
      builder,
      _o.Id,
      _o.ContentGroupId,
      _title);
  }
}

public class ClueEntranceT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("content_group_id")]
  public int ContentGroupId { get; set; }
  [Newtonsoft.Json.JsonProperty("title")]
  public string Title { get; set; }

  public ClueEntranceT() {
    this.Id = 0;
    this.ContentGroupId = 0;
    this.Title = null;
  }
}


static public class ClueEntranceVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*ContentGroupId*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 8 /*Title*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
