// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CompositeRewardDisplay : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CompositeRewardDisplay GetRootAsCompositeRewardDisplay(ByteBuffer _bb) { return GetRootAsCompositeRewardDisplay(_bb, new CompositeRewardDisplay()); }
  public static CompositeRewardDisplay GetRootAsCompositeRewardDisplay(ByteBuffer _bb, CompositeRewardDisplay obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CompositeRewardDisplay __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Title { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTitleBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetTitleBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetTitleArray() { return __p.__vector_as_array<byte>(6); }
  public string ContinueText { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetContinueTextBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetContinueTextBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetContinueTextArray() { return __p.__vector_as_array<byte>(8); }
  public string TitleIconPath { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTitleIconPathBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetTitleIconPathBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetTitleIconPathArray() { return __p.__vector_as_array<byte>(10); }
  public bool IsProgressVisible { get { int o = __p.__offset(12); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string ProgressBarTitle { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetProgressBarTitleBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetProgressBarTitleBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetProgressBarTitleArray() { return __p.__vector_as_array<byte>(14); }
  public int ProgressBarAnimationTime { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)500; } }
  public bool IsItemVisible { get { int o = __p.__offset(18); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool IsSuccess { get { int o = __p.__offset(20); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string AudioId { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAudioIdBytes() { return __p.__vector_as_span<byte>(22, 1); }
#else
  public ArraySegment<byte>? GetAudioIdBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetAudioIdArray() { return __p.__vector_as_array<byte>(22); }

  public static Offset<WWParser.Defs.CompositeRewardDisplay> CreateCompositeRewardDisplay(FlatBufferBuilder builder,
      int id = 0,
      StringOffset titleOffset = default(StringOffset),
      StringOffset continue_textOffset = default(StringOffset),
      StringOffset title_icon_pathOffset = default(StringOffset),
      bool is_progress_visible = false,
      StringOffset progress_bar_titleOffset = default(StringOffset),
      int progress_bar_animation_time = 500,
      bool is_item_visible = false,
      bool is_success = false,
      StringOffset audio_idOffset = default(StringOffset)) {
    builder.StartTable(10);
    CompositeRewardDisplay.AddAudioId(builder, audio_idOffset);
    CompositeRewardDisplay.AddProgressBarAnimationTime(builder, progress_bar_animation_time);
    CompositeRewardDisplay.AddProgressBarTitle(builder, progress_bar_titleOffset);
    CompositeRewardDisplay.AddTitleIconPath(builder, title_icon_pathOffset);
    CompositeRewardDisplay.AddContinueText(builder, continue_textOffset);
    CompositeRewardDisplay.AddTitle(builder, titleOffset);
    CompositeRewardDisplay.AddId(builder, id);
    CompositeRewardDisplay.AddIsSuccess(builder, is_success);
    CompositeRewardDisplay.AddIsItemVisible(builder, is_item_visible);
    CompositeRewardDisplay.AddIsProgressVisible(builder, is_progress_visible);
    return CompositeRewardDisplay.EndCompositeRewardDisplay(builder);
  }

  public static void StartCompositeRewardDisplay(FlatBufferBuilder builder) { builder.StartTable(10); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddTitle(FlatBufferBuilder builder, StringOffset titleOffset) { builder.AddOffset(1, titleOffset.Value, 0); }
  public static void AddContinueText(FlatBufferBuilder builder, StringOffset continueTextOffset) { builder.AddOffset(2, continueTextOffset.Value, 0); }
  public static void AddTitleIconPath(FlatBufferBuilder builder, StringOffset titleIconPathOffset) { builder.AddOffset(3, titleIconPathOffset.Value, 0); }
  public static void AddIsProgressVisible(FlatBufferBuilder builder, bool isProgressVisible) { builder.AddBool(4, isProgressVisible, false); }
  public static void AddProgressBarTitle(FlatBufferBuilder builder, StringOffset progressBarTitleOffset) { builder.AddOffset(5, progressBarTitleOffset.Value, 0); }
  public static void AddProgressBarAnimationTime(FlatBufferBuilder builder, int progressBarAnimationTime) { builder.AddInt(6, progressBarAnimationTime, 500); }
  public static void AddIsItemVisible(FlatBufferBuilder builder, bool isItemVisible) { builder.AddBool(7, isItemVisible, false); }
  public static void AddIsSuccess(FlatBufferBuilder builder, bool isSuccess) { builder.AddBool(8, isSuccess, false); }
  public static void AddAudioId(FlatBufferBuilder builder, StringOffset audioIdOffset) { builder.AddOffset(9, audioIdOffset.Value, 0); }
  public static Offset<WWParser.Defs.CompositeRewardDisplay> EndCompositeRewardDisplay(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.CompositeRewardDisplay>(o);
  }
  public CompositeRewardDisplayT UnPack() {
    var _o = new CompositeRewardDisplayT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CompositeRewardDisplayT _o) {
    _o.Id = this.Id;
    _o.Title = this.Title;
    _o.ContinueText = this.ContinueText;
    _o.TitleIconPath = this.TitleIconPath;
    _o.IsProgressVisible = this.IsProgressVisible;
    _o.ProgressBarTitle = this.ProgressBarTitle;
    _o.ProgressBarAnimationTime = this.ProgressBarAnimationTime;
    _o.IsItemVisible = this.IsItemVisible;
    _o.IsSuccess = this.IsSuccess;
    _o.AudioId = this.AudioId;
  }
  public static Offset<WWParser.Defs.CompositeRewardDisplay> Pack(FlatBufferBuilder builder, CompositeRewardDisplayT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.CompositeRewardDisplay>);
    var _title = _o.Title == null ? default(StringOffset) : builder.CreateString(_o.Title);
    var _continue_text = _o.ContinueText == null ? default(StringOffset) : builder.CreateString(_o.ContinueText);
    var _title_icon_path = _o.TitleIconPath == null ? default(StringOffset) : builder.CreateString(_o.TitleIconPath);
    var _progress_bar_title = _o.ProgressBarTitle == null ? default(StringOffset) : builder.CreateString(_o.ProgressBarTitle);
    var _audio_id = _o.AudioId == null ? default(StringOffset) : builder.CreateString(_o.AudioId);
    return CreateCompositeRewardDisplay(
      builder,
      _o.Id,
      _title,
      _continue_text,
      _title_icon_path,
      _o.IsProgressVisible,
      _progress_bar_title,
      _o.ProgressBarAnimationTime,
      _o.IsItemVisible,
      _o.IsSuccess,
      _audio_id);
  }
}

public class CompositeRewardDisplayT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("title")]
  public string Title { get; set; }
  [Newtonsoft.Json.JsonProperty("continue_text")]
  public string ContinueText { get; set; }
  [Newtonsoft.Json.JsonProperty("title_icon_path")]
  public string TitleIconPath { get; set; }
  [Newtonsoft.Json.JsonProperty("is_progress_visible")]
  public bool IsProgressVisible { get; set; }
  [Newtonsoft.Json.JsonProperty("progress_bar_title")]
  public string ProgressBarTitle { get; set; }
  [Newtonsoft.Json.JsonProperty("progress_bar_animation_time")]
  public int ProgressBarAnimationTime { get; set; }
  [Newtonsoft.Json.JsonProperty("is_item_visible")]
  public bool IsItemVisible { get; set; }
  [Newtonsoft.Json.JsonProperty("is_success")]
  public bool IsSuccess { get; set; }
  [Newtonsoft.Json.JsonProperty("audio_id")]
  public string AudioId { get; set; }

  public CompositeRewardDisplayT() {
    this.Id = 0;
    this.Title = null;
    this.ContinueText = null;
    this.TitleIconPath = null;
    this.IsProgressVisible = false;
    this.ProgressBarTitle = null;
    this.ProgressBarAnimationTime = 500;
    this.IsItemVisible = false;
    this.IsSuccess = false;
    this.AudioId = null;
  }
}


static public class CompositeRewardDisplayVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Title*/, false)
      && verifier.VerifyString(tablePos, 8 /*ContinueText*/, false)
      && verifier.VerifyString(tablePos, 10 /*TitleIconPath*/, false)
      && verifier.VerifyField(tablePos, 12 /*IsProgressVisible*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 14 /*ProgressBarTitle*/, false)
      && verifier.VerifyField(tablePos, 16 /*ProgressBarAnimationTime*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 18 /*IsItemVisible*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 20 /*IsSuccess*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 22 /*AudioId*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
