// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CustomMark : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CustomMark GetRootAsCustomMark(ByteBuffer _bb) { return GetRootAsCustomMark(_bb, new CustomMark()); }
  public static CustomMark GetRootAsCustomMark(ByteBuffer _bb, CustomMark obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CustomMark __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int MarkId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string MarkPic { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMarkPicBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetMarkPicBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetMarkPicArray() { return __p.__vector_as_array<byte>(6); }
  public int ShowRange(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int ShowRangeLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetShowRangeBytes() { return __p.__vector_as_span<int>(8, 4); }
#else
  public ArraySegment<byte>? GetShowRangeBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public int[] GetShowRangeArray() { return __p.__vector_as_array<int>(8); }
  public int ShowPriority { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float Scale { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)1.0f; } }
  public int TrackHudEnable { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float TrackAutoCancelDistance { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)-1.0f; } }

  public static Offset<WWParser.Defs.CustomMark> CreateCustomMark(FlatBufferBuilder builder,
      int mark_id = 0,
      StringOffset mark_picOffset = default(StringOffset),
      VectorOffset show_rangeOffset = default(VectorOffset),
      int show_priority = 0,
      float scale = 1.0f,
      int track_hud_enable = 0,
      float track_auto_cancel_distance = -1.0f) {
    builder.StartTable(7);
    CustomMark.AddTrackAutoCancelDistance(builder, track_auto_cancel_distance);
    CustomMark.AddTrackHudEnable(builder, track_hud_enable);
    CustomMark.AddScale(builder, scale);
    CustomMark.AddShowPriority(builder, show_priority);
    CustomMark.AddShowRange(builder, show_rangeOffset);
    CustomMark.AddMarkPic(builder, mark_picOffset);
    CustomMark.AddMarkId(builder, mark_id);
    return CustomMark.EndCustomMark(builder);
  }

  public static void StartCustomMark(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddMarkId(FlatBufferBuilder builder, int markId) { builder.AddInt(0, markId, 0); }
  public static void AddMarkPic(FlatBufferBuilder builder, StringOffset markPicOffset) { builder.AddOffset(1, markPicOffset.Value, 0); }
  public static void AddShowRange(FlatBufferBuilder builder, VectorOffset showRangeOffset) { builder.AddOffset(2, showRangeOffset.Value, 0); }
  public static VectorOffset CreateShowRangeVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateShowRangeVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateShowRangeVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateShowRangeVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartShowRangeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddShowPriority(FlatBufferBuilder builder, int showPriority) { builder.AddInt(3, showPriority, 0); }
  public static void AddScale(FlatBufferBuilder builder, float scale) { builder.AddFloat(4, scale, 1.0f); }
  public static void AddTrackHudEnable(FlatBufferBuilder builder, int trackHudEnable) { builder.AddInt(5, trackHudEnable, 0); }
  public static void AddTrackAutoCancelDistance(FlatBufferBuilder builder, float trackAutoCancelDistance) { builder.AddFloat(6, trackAutoCancelDistance, -1.0f); }
  public static Offset<WWParser.Defs.CustomMark> EndCustomMark(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.CustomMark>(o);
  }
  public CustomMarkT UnPack() {
    var _o = new CustomMarkT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CustomMarkT _o) {
    _o.MarkId = this.MarkId;
    _o.MarkPic = this.MarkPic;
    _o.ShowRange = new List<int>();
    for (var _j = 0; _j < this.ShowRangeLength; ++_j) {_o.ShowRange.Add(this.ShowRange(_j));}
    _o.ShowPriority = this.ShowPriority;
    _o.Scale = this.Scale;
    _o.TrackHudEnable = this.TrackHudEnable;
    _o.TrackAutoCancelDistance = this.TrackAutoCancelDistance;
  }
  public static Offset<WWParser.Defs.CustomMark> Pack(FlatBufferBuilder builder, CustomMarkT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.CustomMark>);
    var _mark_pic = _o.MarkPic == null ? default(StringOffset) : builder.CreateString(_o.MarkPic);
    var _show_range = default(VectorOffset);
    if (_o.ShowRange != null) {
      var __show_range = _o.ShowRange.ToArray();
      _show_range = CreateShowRangeVector(builder, __show_range);
    }
    return CreateCustomMark(
      builder,
      _o.MarkId,
      _mark_pic,
      _show_range,
      _o.ShowPriority,
      _o.Scale,
      _o.TrackHudEnable,
      _o.TrackAutoCancelDistance);
  }
}

public class CustomMarkT
{
  [Newtonsoft.Json.JsonProperty("mark_id")]
  public int MarkId { get; set; }
  [Newtonsoft.Json.JsonProperty("mark_pic")]
  public string MarkPic { get; set; }
  [Newtonsoft.Json.JsonProperty("show_range")]
  public List<int> ShowRange { get; set; }
  [Newtonsoft.Json.JsonProperty("show_priority")]
  public int ShowPriority { get; set; }
  [Newtonsoft.Json.JsonProperty("scale")]
  public float Scale { get; set; }
  [Newtonsoft.Json.JsonProperty("track_hud_enable")]
  public int TrackHudEnable { get; set; }
  [Newtonsoft.Json.JsonProperty("track_auto_cancel_distance")]
  public float TrackAutoCancelDistance { get; set; }

  public CustomMarkT() {
    this.MarkId = 0;
    this.MarkPic = null;
    this.ShowRange = null;
    this.ShowPriority = 0;
    this.Scale = 1.0f;
    this.TrackHudEnable = 0;
    this.TrackAutoCancelDistance = -1.0f;
  }
}


static public class CustomMarkVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*MarkId*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*MarkPic*/, false)
      && verifier.VerifyVectorOfData(tablePos, 8 /*ShowRange*/, 4 /*int*/, false)
      && verifier.VerifyField(tablePos, 10 /*ShowPriority*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Scale*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*TrackHudEnable*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*TrackAutoCancelDistance*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
