// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FishingEntrustType : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FishingEntrustType GetRootAsFishingEntrustType(ByteBuffer _bb) { return GetRootAsFishingEntrustType(_bb, new FishingEntrustType()); }
  public static FishingEntrustType GetRootAsFishingEntrustType(ByteBuffer _bb, FishingEntrustType obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FishingEntrustType __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public string Color { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetColorBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetColorBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetColorArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<WWParser.Defs.FishingEntrustType> CreateFishingEntrustType(FlatBufferBuilder builder,
      int id = 0,
      StringOffset nameOffset = default(StringOffset),
      StringOffset colorOffset = default(StringOffset)) {
    builder.StartTable(3);
    FishingEntrustType.AddColor(builder, colorOffset);
    FishingEntrustType.AddName(builder, nameOffset);
    FishingEntrustType.AddId(builder, id);
    return FishingEntrustType.EndFishingEntrustType(builder);
  }

  public static void StartFishingEntrustType(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddColor(FlatBufferBuilder builder, StringOffset colorOffset) { builder.AddOffset(2, colorOffset.Value, 0); }
  public static Offset<WWParser.Defs.FishingEntrustType> EndFishingEntrustType(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.FishingEntrustType>(o);
  }
  public FishingEntrustTypeT UnPack() {
    var _o = new FishingEntrustTypeT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FishingEntrustTypeT _o) {
    _o.Id = this.Id;
    _o.Name = this.Name;
    _o.Color = this.Color;
  }
  public static Offset<WWParser.Defs.FishingEntrustType> Pack(FlatBufferBuilder builder, FishingEntrustTypeT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.FishingEntrustType>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    var _color = _o.Color == null ? default(StringOffset) : builder.CreateString(_o.Color);
    return CreateFishingEntrustType(
      builder,
      _o.Id,
      _name,
      _color);
  }
}

public class FishingEntrustTypeT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("name")]
  public string Name { get; set; }
  [Newtonsoft.Json.JsonProperty("color")]
  public string Color { get; set; }

  public FishingEntrustTypeT() {
    this.Id = 0;
    this.Name = null;
    this.Color = null;
  }
}


static public class FishingEntrustTypeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyString(tablePos, 8 /*Color*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
