// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GeographyType : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static GeographyType GetRootAsGeographyType(ByteBuffer _bb) { return GetRootAsGeographyType(_bb, new GeographyType()); }
  public static GeographyType GetRootAsGeographyType(ByteBuffer _bb, GeographyType obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GeographyType __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string TypeDescription { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTypeDescriptionBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetTypeDescriptionBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetTypeDescriptionArray() { return __p.__vector_as_array<byte>(6); }
  public string Icon { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIconBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetIconBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetIconArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<WWParser.Defs.GeographyType> CreateGeographyType(FlatBufferBuilder builder,
      int id = 0,
      StringOffset type_descriptionOffset = default(StringOffset),
      StringOffset iconOffset = default(StringOffset)) {
    builder.StartTable(3);
    GeographyType.AddIcon(builder, iconOffset);
    GeographyType.AddTypeDescription(builder, type_descriptionOffset);
    GeographyType.AddId(builder, id);
    return GeographyType.EndGeographyType(builder);
  }

  public static void StartGeographyType(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddTypeDescription(FlatBufferBuilder builder, StringOffset typeDescriptionOffset) { builder.AddOffset(1, typeDescriptionOffset.Value, 0); }
  public static void AddIcon(FlatBufferBuilder builder, StringOffset iconOffset) { builder.AddOffset(2, iconOffset.Value, 0); }
  public static Offset<WWParser.Defs.GeographyType> EndGeographyType(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.GeographyType>(o);
  }
  public GeographyTypeT UnPack() {
    var _o = new GeographyTypeT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(GeographyTypeT _o) {
    _o.Id = this.Id;
    _o.TypeDescription = this.TypeDescription;
    _o.Icon = this.Icon;
  }
  public static Offset<WWParser.Defs.GeographyType> Pack(FlatBufferBuilder builder, GeographyTypeT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.GeographyType>);
    var _type_description = _o.TypeDescription == null ? default(StringOffset) : builder.CreateString(_o.TypeDescription);
    var _icon = _o.Icon == null ? default(StringOffset) : builder.CreateString(_o.Icon);
    return CreateGeographyType(
      builder,
      _o.Id,
      _type_description,
      _icon);
  }
}

public class GeographyTypeT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("type_description")]
  public string TypeDescription { get; set; }
  [Newtonsoft.Json.JsonProperty("icon")]
  public string Icon { get; set; }

  public GeographyTypeT() {
    this.Id = 0;
    this.TypeDescription = null;
    this.Icon = null;
  }
}


static public class GeographyTypeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*TypeDescription*/, false)
      && verifier.VerifyString(tablePos, 8 /*Icon*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
