// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct IntVector : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static IntVector GetRootAsIntVector(ByteBuffer _bb) { return GetRootAsIntVector(_bb, new IntVector()); }
  public static IntVector GetRootAsIntVector(ByteBuffer _bb, IntVector obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public IntVector __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int X { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Y { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Z { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<WWParser.Defs.IntVector> CreateIntVector(FlatBufferBuilder builder,
      int x = 0,
      int y = 0,
      int z = 0) {
    builder.StartTable(3);
    IntVector.AddZ(builder, z);
    IntVector.AddY(builder, y);
    IntVector.AddX(builder, x);
    return IntVector.EndIntVector(builder);
  }

  public static void StartIntVector(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddX(FlatBufferBuilder builder, int x) { builder.AddInt(0, x, 0); }
  public static void AddY(FlatBufferBuilder builder, int y) { builder.AddInt(1, y, 0); }
  public static void AddZ(FlatBufferBuilder builder, int z) { builder.AddInt(2, z, 0); }
  public static Offset<WWParser.Defs.IntVector> EndIntVector(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.IntVector>(o);
  }
  public IntVectorT UnPack() {
    var _o = new IntVectorT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(IntVectorT _o) {
    _o.X = this.X;
    _o.Y = this.Y;
    _o.Z = this.Z;
  }
  public static Offset<WWParser.Defs.IntVector> Pack(FlatBufferBuilder builder, IntVectorT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.IntVector>);
    return CreateIntVector(
      builder,
      _o.X,
      _o.Y,
      _o.Z);
  }
}

public class IntVectorT
{
  [Newtonsoft.Json.JsonProperty("x")]
  public int X { get; set; }
  [Newtonsoft.Json.JsonProperty("y")]
  public int Y { get; set; }
  [Newtonsoft.Json.JsonProperty("z")]
  public int Z { get; set; }

  public IntVectorT() {
    this.X = 0;
    this.Y = 0;
    this.Z = 0;
  }
}


static public class IntVectorVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*X*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Y*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Z*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
