// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LevelPlayData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static LevelPlayData GetRootAsLevelPlayData(ByteBuffer _bb) { return GetRootAsLevelPlayData(_bb, new LevelPlayData()); }
  public static LevelPlayData GetRootAsLevelPlayData(ByteBuffer _bb, LevelPlayData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LevelPlayData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int LevelPlayId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Data { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDataBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDataBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDataArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<WWParser.Defs.LevelPlayData> CreateLevelPlayData(FlatBufferBuilder builder,
      int level_play_id = 0,
      StringOffset dataOffset = default(StringOffset)) {
    builder.StartTable(2);
    LevelPlayData.AddData(builder, dataOffset);
    LevelPlayData.AddLevelPlayId(builder, level_play_id);
    return LevelPlayData.EndLevelPlayData(builder);
  }

  public static void StartLevelPlayData(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddLevelPlayId(FlatBufferBuilder builder, int levelPlayId) { builder.AddInt(0, levelPlayId, 0); }
  public static void AddData(FlatBufferBuilder builder, StringOffset dataOffset) { builder.AddOffset(1, dataOffset.Value, 0); }
  public static Offset<WWParser.Defs.LevelPlayData> EndLevelPlayData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.LevelPlayData>(o);
  }
  public LevelPlayDataT UnPack() {
    var _o = new LevelPlayDataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(LevelPlayDataT _o) {
    _o.LevelPlayId = this.LevelPlayId;
    _o.Data = this.Data;
  }
  public static Offset<WWParser.Defs.LevelPlayData> Pack(FlatBufferBuilder builder, LevelPlayDataT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.LevelPlayData>);
    var _data = _o.Data == null ? default(StringOffset) : builder.CreateString(_o.Data);
    return CreateLevelPlayData(
      builder,
      _o.LevelPlayId,
      _data);
  }
}

public class LevelPlayDataT
{
  [Newtonsoft.Json.JsonProperty("level_play_id")]
  public int LevelPlayId { get; set; }
  [Newtonsoft.Json.JsonProperty("data")]
  public string Data { get; set; }

  public LevelPlayDataT() {
    this.LevelPlayId = 0;
    this.Data = null;
  }
}


static public class LevelPlayDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*LevelPlayId*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Data*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
