// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MonsterDetectionFilter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MonsterDetectionFilter GetRootAsMonsterDetectionFilter(ByteBuffer _bb) { return GetRootAsMonsterDetectionFilter(_bb, new MonsterDetectionFilter()); }
  public static MonsterDetectionFilter GetRootAsMonsterDetectionFilter(ByteBuffer _bb, MonsterDetectionFilter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MonsterDetectionFilter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int EntityConfigId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<WWParser.Defs.MonsterDetectionFilter> CreateMonsterDetectionFilter(FlatBufferBuilder builder,
      int id = 0,
      int entity_config_id = 0) {
    builder.StartTable(2);
    MonsterDetectionFilter.AddEntityConfigId(builder, entity_config_id);
    MonsterDetectionFilter.AddId(builder, id);
    return MonsterDetectionFilter.EndMonsterDetectionFilter(builder);
  }

  public static void StartMonsterDetectionFilter(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddEntityConfigId(FlatBufferBuilder builder, int entityConfigId) { builder.AddInt(1, entityConfigId, 0); }
  public static Offset<WWParser.Defs.MonsterDetectionFilter> EndMonsterDetectionFilter(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.MonsterDetectionFilter>(o);
  }
  public MonsterDetectionFilterT UnPack() {
    var _o = new MonsterDetectionFilterT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(MonsterDetectionFilterT _o) {
    _o.Id = this.Id;
    _o.EntityConfigId = this.EntityConfigId;
  }
  public static Offset<WWParser.Defs.MonsterDetectionFilter> Pack(FlatBufferBuilder builder, MonsterDetectionFilterT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.MonsterDetectionFilter>);
    return CreateMonsterDetectionFilter(
      builder,
      _o.Id,
      _o.EntityConfigId);
  }
}

public class MonsterDetectionFilterT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("entity_config_id")]
  public int EntityConfigId { get; set; }

  public MonsterDetectionFilterT() {
    this.Id = 0;
    this.EntityConfigId = 0;
  }
}


static public class MonsterDetectionFilterVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*EntityConfigId*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
