// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PhysicsAssetConfig : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static PhysicsAssetConfig GetRootAsPhysicsAssetConfig(ByteBuffer _bb) { return GetRootAsPhysicsAssetConfig(_bb, new PhysicsAssetConfig()); }
  public static PhysicsAssetConfig GetRootAsPhysicsAssetConfig(ByteBuffer _bb, PhysicsAssetConfig obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PhysicsAssetConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetIdArray() { return __p.__vector_as_array<byte>(4); }
  public string PhysicsAssetPath { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPhysicsAssetPathBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetPhysicsAssetPathBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPhysicsAssetPathArray() { return __p.__vector_as_array<byte>(6); }
  public string BoneNames(int j) { int o = __p.__offset(8); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int BoneNamesLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<WWParser.Defs.PhysicsAssetConfig> CreatePhysicsAssetConfig(FlatBufferBuilder builder,
      StringOffset idOffset = default(StringOffset),
      StringOffset physics_asset_pathOffset = default(StringOffset),
      VectorOffset bone_namesOffset = default(VectorOffset)) {
    builder.StartTable(3);
    PhysicsAssetConfig.AddBoneNames(builder, bone_namesOffset);
    PhysicsAssetConfig.AddPhysicsAssetPath(builder, physics_asset_pathOffset);
    PhysicsAssetConfig.AddId(builder, idOffset);
    return PhysicsAssetConfig.EndPhysicsAssetConfig(builder);
  }

  public static void StartPhysicsAssetConfig(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(0, idOffset.Value, 0); }
  public static void AddPhysicsAssetPath(FlatBufferBuilder builder, StringOffset physicsAssetPathOffset) { builder.AddOffset(1, physicsAssetPathOffset.Value, 0); }
  public static void AddBoneNames(FlatBufferBuilder builder, VectorOffset boneNamesOffset) { builder.AddOffset(2, boneNamesOffset.Value, 0); }
  public static VectorOffset CreateBoneNamesVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateBoneNamesVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBoneNamesVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBoneNamesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartBoneNamesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<WWParser.Defs.PhysicsAssetConfig> EndPhysicsAssetConfig(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.PhysicsAssetConfig>(o);
  }
  public PhysicsAssetConfigT UnPack() {
    var _o = new PhysicsAssetConfigT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(PhysicsAssetConfigT _o) {
    _o.Id = this.Id;
    _o.PhysicsAssetPath = this.PhysicsAssetPath;
    _o.BoneNames = new List<string>();
    for (var _j = 0; _j < this.BoneNamesLength; ++_j) {_o.BoneNames.Add(this.BoneNames(_j));}
  }
  public static Offset<WWParser.Defs.PhysicsAssetConfig> Pack(FlatBufferBuilder builder, PhysicsAssetConfigT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.PhysicsAssetConfig>);
    var _id = _o.Id == null ? default(StringOffset) : builder.CreateString(_o.Id);
    var _physics_asset_path = _o.PhysicsAssetPath == null ? default(StringOffset) : builder.CreateString(_o.PhysicsAssetPath);
    var _bone_names = default(VectorOffset);
    if (_o.BoneNames != null) {
      var __bone_names = new StringOffset[_o.BoneNames.Count];
      for (var _j = 0; _j < __bone_names.Length; ++_j) { __bone_names[_j] = builder.CreateString(_o.BoneNames[_j]); }
      _bone_names = CreateBoneNamesVector(builder, __bone_names);
    }
    return CreatePhysicsAssetConfig(
      builder,
      _id,
      _physics_asset_path,
      _bone_names);
  }
}

public class PhysicsAssetConfigT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public string Id { get; set; }
  [Newtonsoft.Json.JsonProperty("physics_asset_path")]
  public string PhysicsAssetPath { get; set; }
  [Newtonsoft.Json.JsonProperty("bone_names")]
  public List<string> BoneNames { get; set; }

  public PhysicsAssetConfigT() {
    this.Id = null;
    this.PhysicsAssetPath = null;
    this.BoneNames = null;
  }
}


static public class PhysicsAssetConfigVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Id*/, false)
      && verifier.VerifyString(tablePos, 6 /*PhysicsAssetPath*/, false)
      && verifier.VerifyVectorOfStrings(tablePos, 8 /*BoneNames*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
