// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RacingBettingGear : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static RacingBettingGear GetRootAsRacingBettingGear(ByteBuffer _bb) { return GetRootAsRacingBettingGear(_bb, new RacingBettingGear()); }
  public static RacingBettingGear GetRootAsRacingBettingGear(ByteBuffer _bb, RacingBettingGear obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RacingBettingGear __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int SeasonId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Odds { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<WWParser.Defs.RacingBettingGear> CreateRacingBettingGear(FlatBufferBuilder builder,
      int id = 0,
      int season_id = 0,
      int odds = 0) {
    builder.StartTable(3);
    RacingBettingGear.AddOdds(builder, odds);
    RacingBettingGear.AddSeasonId(builder, season_id);
    RacingBettingGear.AddId(builder, id);
    return RacingBettingGear.EndRacingBettingGear(builder);
  }

  public static void StartRacingBettingGear(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddSeasonId(FlatBufferBuilder builder, int seasonId) { builder.AddInt(1, seasonId, 0); }
  public static void AddOdds(FlatBufferBuilder builder, int odds) { builder.AddInt(2, odds, 0); }
  public static Offset<WWParser.Defs.RacingBettingGear> EndRacingBettingGear(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.RacingBettingGear>(o);
  }
  public RacingBettingGearT UnPack() {
    var _o = new RacingBettingGearT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(RacingBettingGearT _o) {
    _o.Id = this.Id;
    _o.SeasonId = this.SeasonId;
    _o.Odds = this.Odds;
  }
  public static Offset<WWParser.Defs.RacingBettingGear> Pack(FlatBufferBuilder builder, RacingBettingGearT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.RacingBettingGear>);
    return CreateRacingBettingGear(
      builder,
      _o.Id,
      _o.SeasonId,
      _o.Odds);
  }
}

public class RacingBettingGearT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("season_id")]
  public int SeasonId { get; set; }
  [Newtonsoft.Json.JsonProperty("odds")]
  public int Odds { get; set; }

  public RacingBettingGearT() {
    this.Id = 0;
    this.SeasonId = 0;
    this.Odds = 0;
  }
}


static public class RacingBettingGearVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*SeasonId*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Odds*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
