// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RogueResEventBgm : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static RogueResEventBgm GetRootAsRogueResEventBgm(ByteBuffer _bb) { return GetRootAsRogueResEventBgm(_bb, new RogueResEventBgm()); }
  public static RogueResEventBgm GetRootAsRogueResEventBgm(ByteBuffer _bb, RogueResEventBgm obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RogueResEventBgm __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string BgmName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBgmNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetBgmNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetBgmNameArray() { return __p.__vector_as_array<byte>(6); }
  public string BgmPath { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBgmPathBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetBgmPathBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetBgmPathArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<WWParser.Defs.RogueResEventBgm> CreateRogueResEventBgm(FlatBufferBuilder builder,
      int id = 0,
      StringOffset bgm_nameOffset = default(StringOffset),
      StringOffset bgm_pathOffset = default(StringOffset)) {
    builder.StartTable(3);
    RogueResEventBgm.AddBgmPath(builder, bgm_pathOffset);
    RogueResEventBgm.AddBgmName(builder, bgm_nameOffset);
    RogueResEventBgm.AddId(builder, id);
    return RogueResEventBgm.EndRogueResEventBgm(builder);
  }

  public static void StartRogueResEventBgm(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddBgmName(FlatBufferBuilder builder, StringOffset bgmNameOffset) { builder.AddOffset(1, bgmNameOffset.Value, 0); }
  public static void AddBgmPath(FlatBufferBuilder builder, StringOffset bgmPathOffset) { builder.AddOffset(2, bgmPathOffset.Value, 0); }
  public static Offset<WWParser.Defs.RogueResEventBgm> EndRogueResEventBgm(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.RogueResEventBgm>(o);
  }
  public RogueResEventBgmT UnPack() {
    var _o = new RogueResEventBgmT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(RogueResEventBgmT _o) {
    _o.Id = this.Id;
    _o.BgmName = this.BgmName;
    _o.BgmPath = this.BgmPath;
  }
  public static Offset<WWParser.Defs.RogueResEventBgm> Pack(FlatBufferBuilder builder, RogueResEventBgmT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.RogueResEventBgm>);
    var _bgm_name = _o.BgmName == null ? default(StringOffset) : builder.CreateString(_o.BgmName);
    var _bgm_path = _o.BgmPath == null ? default(StringOffset) : builder.CreateString(_o.BgmPath);
    return CreateRogueResEventBgm(
      builder,
      _o.Id,
      _bgm_name,
      _bgm_path);
  }
}

public class RogueResEventBgmT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("bgm_name")]
  public string BgmName { get; set; }
  [Newtonsoft.Json.JsonProperty("bgm_path")]
  public string BgmPath { get; set; }

  public RogueResEventBgmT() {
    this.Id = 0;
    this.BgmName = null;
    this.BgmPath = null;
  }
}


static public class RogueResEventBgmVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*BgmName*/, false)
      && verifier.VerifyString(tablePos, 8 /*BgmPath*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
