// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RogueWeeklyBuffDesc : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static RogueWeeklyBuffDesc GetRootAsRogueWeeklyBuffDesc(ByteBuffer _bb) { return GetRootAsRogueWeeklyBuffDesc(_bb, new RogueWeeklyBuffDesc()); }
  public static RogueWeeklyBuffDesc GetRootAsRogueWeeklyBuffDesc(ByteBuffer _bb, RogueWeeklyBuffDesc obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RogueWeeklyBuffDesc __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string BuffDsec { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBuffDsecBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetBuffDsecBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetBuffDsecArray() { return __p.__vector_as_array<byte>(6); }
  public string BuffDsecParam(int j) { int o = __p.__offset(8); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int BuffDsecParamLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<WWParser.Defs.RogueWeeklyBuffDesc> CreateRogueWeeklyBuffDesc(FlatBufferBuilder builder,
      int id = 0,
      StringOffset buff_dsecOffset = default(StringOffset),
      VectorOffset buff_dsec_paramOffset = default(VectorOffset)) {
    builder.StartTable(3);
    RogueWeeklyBuffDesc.AddBuffDsecParam(builder, buff_dsec_paramOffset);
    RogueWeeklyBuffDesc.AddBuffDsec(builder, buff_dsecOffset);
    RogueWeeklyBuffDesc.AddId(builder, id);
    return RogueWeeklyBuffDesc.EndRogueWeeklyBuffDesc(builder);
  }

  public static void StartRogueWeeklyBuffDesc(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddBuffDsec(FlatBufferBuilder builder, StringOffset buffDsecOffset) { builder.AddOffset(1, buffDsecOffset.Value, 0); }
  public static void AddBuffDsecParam(FlatBufferBuilder builder, VectorOffset buffDsecParamOffset) { builder.AddOffset(2, buffDsecParamOffset.Value, 0); }
  public static VectorOffset CreateBuffDsecParamVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateBuffDsecParamVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBuffDsecParamVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBuffDsecParamVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartBuffDsecParamVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<WWParser.Defs.RogueWeeklyBuffDesc> EndRogueWeeklyBuffDesc(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.RogueWeeklyBuffDesc>(o);
  }
  public RogueWeeklyBuffDescT UnPack() {
    var _o = new RogueWeeklyBuffDescT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(RogueWeeklyBuffDescT _o) {
    _o.Id = this.Id;
    _o.BuffDsec = this.BuffDsec;
    _o.BuffDsecParam = new List<string>();
    for (var _j = 0; _j < this.BuffDsecParamLength; ++_j) {_o.BuffDsecParam.Add(this.BuffDsecParam(_j));}
  }
  public static Offset<WWParser.Defs.RogueWeeklyBuffDesc> Pack(FlatBufferBuilder builder, RogueWeeklyBuffDescT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.RogueWeeklyBuffDesc>);
    var _buff_dsec = _o.BuffDsec == null ? default(StringOffset) : builder.CreateString(_o.BuffDsec);
    var _buff_dsec_param = default(VectorOffset);
    if (_o.BuffDsecParam != null) {
      var __buff_dsec_param = new StringOffset[_o.BuffDsecParam.Count];
      for (var _j = 0; _j < __buff_dsec_param.Length; ++_j) { __buff_dsec_param[_j] = builder.CreateString(_o.BuffDsecParam[_j]); }
      _buff_dsec_param = CreateBuffDsecParamVector(builder, __buff_dsec_param);
    }
    return CreateRogueWeeklyBuffDesc(
      builder,
      _o.Id,
      _buff_dsec,
      _buff_dsec_param);
  }
}

public class RogueWeeklyBuffDescT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("buff_dsec")]
  public string BuffDsec { get; set; }
  [Newtonsoft.Json.JsonProperty("buff_dsec_param")]
  public List<string> BuffDsecParam { get; set; }

  public RogueWeeklyBuffDescT() {
    this.Id = 0;
    this.BuffDsec = null;
    this.BuffDsecParam = null;
  }
}


static public class RogueWeeklyBuffDescVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*BuffDsec*/, false)
      && verifier.VerifyVectorOfStrings(tablePos, 8 /*BuffDsecParam*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
