// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RoleTrialUiConfig : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static RoleTrialUiConfig GetRootAsRoleTrialUiConfig(ByteBuffer _bb) { return GetRootAsRoleTrialUiConfig(_bb, new RoleTrialUiConfig()); }
  public static RoleTrialUiConfig GetRootAsRoleTrialUiConfig(ByteBuffer _bb, RoleTrialUiConfig obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RoleTrialUiConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Color1 { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetColor1Bytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetColor1Bytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetColor1Array() { return __p.__vector_as_array<byte>(6); }
  public string Color2 { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetColor2Bytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetColor2Bytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetColor2Array() { return __p.__vector_as_array<byte>(8); }
  public string Color3 { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetColor3Bytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetColor3Bytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetColor3Array() { return __p.__vector_as_array<byte>(10); }
  public string Color4 { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetColor4Bytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetColor4Bytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetColor4Array() { return __p.__vector_as_array<byte>(12); }
  public string Color5 { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetColor5Bytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetColor5Bytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetColor5Array() { return __p.__vector_as_array<byte>(14); }

  public static Offset<WWParser.Defs.RoleTrialUiConfig> CreateRoleTrialUiConfig(FlatBufferBuilder builder,
      int id = 0,
      StringOffset color1Offset = default(StringOffset),
      StringOffset color2Offset = default(StringOffset),
      StringOffset color3Offset = default(StringOffset),
      StringOffset color4Offset = default(StringOffset),
      StringOffset color5Offset = default(StringOffset)) {
    builder.StartTable(6);
    RoleTrialUiConfig.AddColor5(builder, color5Offset);
    RoleTrialUiConfig.AddColor4(builder, color4Offset);
    RoleTrialUiConfig.AddColor3(builder, color3Offset);
    RoleTrialUiConfig.AddColor2(builder, color2Offset);
    RoleTrialUiConfig.AddColor1(builder, color1Offset);
    RoleTrialUiConfig.AddId(builder, id);
    return RoleTrialUiConfig.EndRoleTrialUiConfig(builder);
  }

  public static void StartRoleTrialUiConfig(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddColor1(FlatBufferBuilder builder, StringOffset color1Offset) { builder.AddOffset(1, color1Offset.Value, 0); }
  public static void AddColor2(FlatBufferBuilder builder, StringOffset color2Offset) { builder.AddOffset(2, color2Offset.Value, 0); }
  public static void AddColor3(FlatBufferBuilder builder, StringOffset color3Offset) { builder.AddOffset(3, color3Offset.Value, 0); }
  public static void AddColor4(FlatBufferBuilder builder, StringOffset color4Offset) { builder.AddOffset(4, color4Offset.Value, 0); }
  public static void AddColor5(FlatBufferBuilder builder, StringOffset color5Offset) { builder.AddOffset(5, color5Offset.Value, 0); }
  public static Offset<WWParser.Defs.RoleTrialUiConfig> EndRoleTrialUiConfig(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.RoleTrialUiConfig>(o);
  }
  public RoleTrialUiConfigT UnPack() {
    var _o = new RoleTrialUiConfigT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(RoleTrialUiConfigT _o) {
    _o.Id = this.Id;
    _o.Color1 = this.Color1;
    _o.Color2 = this.Color2;
    _o.Color3 = this.Color3;
    _o.Color4 = this.Color4;
    _o.Color5 = this.Color5;
  }
  public static Offset<WWParser.Defs.RoleTrialUiConfig> Pack(FlatBufferBuilder builder, RoleTrialUiConfigT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.RoleTrialUiConfig>);
    var _color1 = _o.Color1 == null ? default(StringOffset) : builder.CreateString(_o.Color1);
    var _color2 = _o.Color2 == null ? default(StringOffset) : builder.CreateString(_o.Color2);
    var _color3 = _o.Color3 == null ? default(StringOffset) : builder.CreateString(_o.Color3);
    var _color4 = _o.Color4 == null ? default(StringOffset) : builder.CreateString(_o.Color4);
    var _color5 = _o.Color5 == null ? default(StringOffset) : builder.CreateString(_o.Color5);
    return CreateRoleTrialUiConfig(
      builder,
      _o.Id,
      _color1,
      _color2,
      _color3,
      _color4,
      _color5);
  }
}

public class RoleTrialUiConfigT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("color1")]
  public string Color1 { get; set; }
  [Newtonsoft.Json.JsonProperty("color2")]
  public string Color2 { get; set; }
  [Newtonsoft.Json.JsonProperty("color3")]
  public string Color3 { get; set; }
  [Newtonsoft.Json.JsonProperty("color4")]
  public string Color4 { get; set; }
  [Newtonsoft.Json.JsonProperty("color5")]
  public string Color5 { get; set; }

  public RoleTrialUiConfigT() {
    this.Id = 0;
    this.Color1 = null;
    this.Color2 = null;
    this.Color3 = null;
    this.Color4 = null;
    this.Color5 = null;
  }
}


static public class RoleTrialUiConfigVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Color1*/, false)
      && verifier.VerifyString(tablePos, 8 /*Color2*/, false)
      && verifier.VerifyString(tablePos, 10 /*Color3*/, false)
      && verifier.VerifyString(tablePos, 12 /*Color4*/, false)
      && verifier.VerifyString(tablePos, 14 /*Color5*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
