// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RoleDevelopCurve : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static RoleDevelopCurve GetRootAsRoleDevelopCurve(ByteBuffer _bb) { return GetRootAsRoleDevelopCurve(_bb, new RoleDevelopCurve()); }
  public static RoleDevelopCurve GetRootAsRoleDevelopCurve(ByteBuffer _bb, RoleDevelopCurve obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RoleDevelopCurve __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int GroupId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int TrainType { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string TrainContent { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTrainContentBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetTrainContentBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetTrainContentArray() { return __p.__vector_as_array<byte>(10); }
  public int WishConsume { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<WWParser.Defs.RoleDevelopCurve> CreateRoleDevelopCurve(FlatBufferBuilder builder,
      int id = 0,
      int group_id = 0,
      int train_type = 0,
      StringOffset train_contentOffset = default(StringOffset),
      int wish_consume = 0) {
    builder.StartTable(5);
    RoleDevelopCurve.AddWishConsume(builder, wish_consume);
    RoleDevelopCurve.AddTrainContent(builder, train_contentOffset);
    RoleDevelopCurve.AddTrainType(builder, train_type);
    RoleDevelopCurve.AddGroupId(builder, group_id);
    RoleDevelopCurve.AddId(builder, id);
    return RoleDevelopCurve.EndRoleDevelopCurve(builder);
  }

  public static void StartRoleDevelopCurve(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddGroupId(FlatBufferBuilder builder, int groupId) { builder.AddInt(1, groupId, 0); }
  public static void AddTrainType(FlatBufferBuilder builder, int trainType) { builder.AddInt(2, trainType, 0); }
  public static void AddTrainContent(FlatBufferBuilder builder, StringOffset trainContentOffset) { builder.AddOffset(3, trainContentOffset.Value, 0); }
  public static void AddWishConsume(FlatBufferBuilder builder, int wishConsume) { builder.AddInt(4, wishConsume, 0); }
  public static Offset<WWParser.Defs.RoleDevelopCurve> EndRoleDevelopCurve(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.RoleDevelopCurve>(o);
  }
  public RoleDevelopCurveT UnPack() {
    var _o = new RoleDevelopCurveT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(RoleDevelopCurveT _o) {
    _o.Id = this.Id;
    _o.GroupId = this.GroupId;
    _o.TrainType = this.TrainType;
    _o.TrainContent = this.TrainContent;
    _o.WishConsume = this.WishConsume;
  }
  public static Offset<WWParser.Defs.RoleDevelopCurve> Pack(FlatBufferBuilder builder, RoleDevelopCurveT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.RoleDevelopCurve>);
    var _train_content = _o.TrainContent == null ? default(StringOffset) : builder.CreateString(_o.TrainContent);
    return CreateRoleDevelopCurve(
      builder,
      _o.Id,
      _o.GroupId,
      _o.TrainType,
      _train_content,
      _o.WishConsume);
  }
}

public class RoleDevelopCurveT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("group_id")]
  public int GroupId { get; set; }
  [Newtonsoft.Json.JsonProperty("train_type")]
  public int TrainType { get; set; }
  [Newtonsoft.Json.JsonProperty("train_content")]
  public string TrainContent { get; set; }
  [Newtonsoft.Json.JsonProperty("wish_consume")]
  public int WishConsume { get; set; }

  public RoleDevelopCurveT() {
    this.Id = 0;
    this.GroupId = 0;
    this.TrainType = 0;
    this.TrainContent = null;
    this.WishConsume = 0;
  }
}


static public class RoleDevelopCurveVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*GroupId*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*TrainType*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 10 /*TrainContent*/, false)
      && verifier.VerifyField(tablePos, 12 /*WishConsume*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
