// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RougeResMiraclecreation : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static RougeResMiraclecreation GetRootAsRougeResMiraclecreation(ByteBuffer _bb) { return GetRootAsRougeResMiraclecreation(_bb, new RougeResMiraclecreation()); }
  public static RougeResMiraclecreation GetRootAsRougeResMiraclecreation(ByteBuffer _bb, RougeResMiraclecreation obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RougeResMiraclecreation __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Category { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int DefaultLevel { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Level { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MaxLevel { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Icon { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIconBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetIconBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetIconArray() { return __p.__vector_as_array<byte>(14); }
  public string Name { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(16); }
  public string BriefDescribe { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBriefDescribeBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetBriefDescribeBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetBriefDescribeArray() { return __p.__vector_as_array<byte>(18); }
  public string Describe { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescribeBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetDescribeBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetDescribeArray() { return __p.__vector_as_array<byte>(20); }
  public string StoryDescribe { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetStoryDescribeBytes() { return __p.__vector_as_span<byte>(22, 1); }
#else
  public ArraySegment<byte>? GetStoryDescribeBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetStoryDescribeArray() { return __p.__vector_as_array<byte>(22); }

  public static Offset<WWParser.Defs.RougeResMiraclecreation> CreateRougeResMiraclecreation(FlatBufferBuilder builder,
      int id = 0,
      int category = 0,
      int default_level = 0,
      int level = 0,
      int max_level = 0,
      StringOffset iconOffset = default(StringOffset),
      StringOffset nameOffset = default(StringOffset),
      StringOffset brief_describeOffset = default(StringOffset),
      StringOffset describeOffset = default(StringOffset),
      StringOffset story_describeOffset = default(StringOffset)) {
    builder.StartTable(10);
    RougeResMiraclecreation.AddStoryDescribe(builder, story_describeOffset);
    RougeResMiraclecreation.AddDescribe(builder, describeOffset);
    RougeResMiraclecreation.AddBriefDescribe(builder, brief_describeOffset);
    RougeResMiraclecreation.AddName(builder, nameOffset);
    RougeResMiraclecreation.AddIcon(builder, iconOffset);
    RougeResMiraclecreation.AddMaxLevel(builder, max_level);
    RougeResMiraclecreation.AddLevel(builder, level);
    RougeResMiraclecreation.AddDefaultLevel(builder, default_level);
    RougeResMiraclecreation.AddCategory(builder, category);
    RougeResMiraclecreation.AddId(builder, id);
    return RougeResMiraclecreation.EndRougeResMiraclecreation(builder);
  }

  public static void StartRougeResMiraclecreation(FlatBufferBuilder builder) { builder.StartTable(10); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddCategory(FlatBufferBuilder builder, int category) { builder.AddInt(1, category, 0); }
  public static void AddDefaultLevel(FlatBufferBuilder builder, int defaultLevel) { builder.AddInt(2, defaultLevel, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(3, level, 0); }
  public static void AddMaxLevel(FlatBufferBuilder builder, int maxLevel) { builder.AddInt(4, maxLevel, 0); }
  public static void AddIcon(FlatBufferBuilder builder, StringOffset iconOffset) { builder.AddOffset(5, iconOffset.Value, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(6, nameOffset.Value, 0); }
  public static void AddBriefDescribe(FlatBufferBuilder builder, StringOffset briefDescribeOffset) { builder.AddOffset(7, briefDescribeOffset.Value, 0); }
  public static void AddDescribe(FlatBufferBuilder builder, StringOffset describeOffset) { builder.AddOffset(8, describeOffset.Value, 0); }
  public static void AddStoryDescribe(FlatBufferBuilder builder, StringOffset storyDescribeOffset) { builder.AddOffset(9, storyDescribeOffset.Value, 0); }
  public static Offset<WWParser.Defs.RougeResMiraclecreation> EndRougeResMiraclecreation(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.RougeResMiraclecreation>(o);
  }
  public RougeResMiraclecreationT UnPack() {
    var _o = new RougeResMiraclecreationT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(RougeResMiraclecreationT _o) {
    _o.Id = this.Id;
    _o.Category = this.Category;
    _o.DefaultLevel = this.DefaultLevel;
    _o.Level = this.Level;
    _o.MaxLevel = this.MaxLevel;
    _o.Icon = this.Icon;
    _o.Name = this.Name;
    _o.BriefDescribe = this.BriefDescribe;
    _o.Describe = this.Describe;
    _o.StoryDescribe = this.StoryDescribe;
  }
  public static Offset<WWParser.Defs.RougeResMiraclecreation> Pack(FlatBufferBuilder builder, RougeResMiraclecreationT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.RougeResMiraclecreation>);
    var _icon = _o.Icon == null ? default(StringOffset) : builder.CreateString(_o.Icon);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    var _brief_describe = _o.BriefDescribe == null ? default(StringOffset) : builder.CreateString(_o.BriefDescribe);
    var _describe = _o.Describe == null ? default(StringOffset) : builder.CreateString(_o.Describe);
    var _story_describe = _o.StoryDescribe == null ? default(StringOffset) : builder.CreateString(_o.StoryDescribe);
    return CreateRougeResMiraclecreation(
      builder,
      _o.Id,
      _o.Category,
      _o.DefaultLevel,
      _o.Level,
      _o.MaxLevel,
      _icon,
      _name,
      _brief_describe,
      _describe,
      _story_describe);
  }
}

public class RougeResMiraclecreationT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("category")]
  public int Category { get; set; }
  [Newtonsoft.Json.JsonProperty("default_level")]
  public int DefaultLevel { get; set; }
  [Newtonsoft.Json.JsonProperty("level")]
  public int Level { get; set; }
  [Newtonsoft.Json.JsonProperty("max_level")]
  public int MaxLevel { get; set; }
  [Newtonsoft.Json.JsonProperty("icon")]
  public string Icon { get; set; }
  [Newtonsoft.Json.JsonProperty("name")]
  public string Name { get; set; }
  [Newtonsoft.Json.JsonProperty("brief_describe")]
  public string BriefDescribe { get; set; }
  [Newtonsoft.Json.JsonProperty("describe")]
  public string Describe { get; set; }
  [Newtonsoft.Json.JsonProperty("story_describe")]
  public string StoryDescribe { get; set; }

  public RougeResMiraclecreationT() {
    this.Id = 0;
    this.Category = 0;
    this.DefaultLevel = 0;
    this.Level = 0;
    this.MaxLevel = 0;
    this.Icon = null;
    this.Name = null;
    this.BriefDescribe = null;
    this.Describe = null;
    this.StoryDescribe = null;
  }
}


static public class RougeResMiraclecreationVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Category*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*DefaultLevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Level*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*MaxLevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 14 /*Icon*/, false)
      && verifier.VerifyString(tablePos, 16 /*Name*/, false)
      && verifier.VerifyString(tablePos, 18 /*BriefDescribe*/, false)
      && verifier.VerifyString(tablePos, 20 /*Describe*/, false)
      && verifier.VerifyString(tablePos, 22 /*StoryDescribe*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
