// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TalkOptionIcon : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static TalkOptionIcon GetRootAsTalkOptionIcon(ByteBuffer _bb) { return GetRootAsTalkOptionIcon(_bb, new TalkOptionIcon()); }
  public static TalkOptionIcon GetRootAsTalkOptionIcon(ByteBuffer _bb, TalkOptionIcon obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TalkOptionIcon __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Type { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTypeBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetTypeBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetTypeArray() { return __p.__vector_as_array<byte>(6); }
  public string Icon { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIconBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetIconBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetIconArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<WWParser.Defs.TalkOptionIcon> CreateTalkOptionIcon(FlatBufferBuilder builder,
      int id = 0,
      StringOffset typeOffset = default(StringOffset),
      StringOffset iconOffset = default(StringOffset)) {
    builder.StartTable(3);
    TalkOptionIcon.AddIcon(builder, iconOffset);
    TalkOptionIcon.AddType(builder, typeOffset);
    TalkOptionIcon.AddId(builder, id);
    return TalkOptionIcon.EndTalkOptionIcon(builder);
  }

  public static void StartTalkOptionIcon(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddType(FlatBufferBuilder builder, StringOffset typeOffset) { builder.AddOffset(1, typeOffset.Value, 0); }
  public static void AddIcon(FlatBufferBuilder builder, StringOffset iconOffset) { builder.AddOffset(2, iconOffset.Value, 0); }
  public static Offset<WWParser.Defs.TalkOptionIcon> EndTalkOptionIcon(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.TalkOptionIcon>(o);
  }
  public TalkOptionIconT UnPack() {
    var _o = new TalkOptionIconT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TalkOptionIconT _o) {
    _o.Id = this.Id;
    _o.Type = this.Type;
    _o.Icon = this.Icon;
  }
  public static Offset<WWParser.Defs.TalkOptionIcon> Pack(FlatBufferBuilder builder, TalkOptionIconT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.TalkOptionIcon>);
    var _type = _o.Type == null ? default(StringOffset) : builder.CreateString(_o.Type);
    var _icon = _o.Icon == null ? default(StringOffset) : builder.CreateString(_o.Icon);
    return CreateTalkOptionIcon(
      builder,
      _o.Id,
      _type,
      _icon);
  }
}

public class TalkOptionIconT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("type")]
  public string Type { get; set; }
  [Newtonsoft.Json.JsonProperty("icon")]
  public string Icon { get; set; }

  public TalkOptionIconT() {
    this.Id = 0;
    this.Type = null;
    this.Icon = null;
  }
}


static public class TalkOptionIconVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Type*/, false)
      && verifier.VerifyString(tablePos, 8 /*Icon*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
