// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TrackMoonHandbookReward : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static TrackMoonHandbookReward GetRootAsTrackMoonHandbookReward(ByteBuffer _bb) { return GetRootAsTrackMoonHandbookReward(_bb, new TrackMoonHandbookReward()); }
  public static TrackMoonHandbookReward GetRootAsTrackMoonHandbookReward(ByteBuffer _bb, TrackMoonHandbookReward obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TrackMoonHandbookReward __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Goal { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int RewardInfo { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<WWParser.Defs.TrackMoonHandbookReward> CreateTrackMoonHandbookReward(FlatBufferBuilder builder,
      int id = 0,
      int goal = 0,
      int reward_info = 0) {
    builder.StartTable(3);
    TrackMoonHandbookReward.AddRewardInfo(builder, reward_info);
    TrackMoonHandbookReward.AddGoal(builder, goal);
    TrackMoonHandbookReward.AddId(builder, id);
    return TrackMoonHandbookReward.EndTrackMoonHandbookReward(builder);
  }

  public static void StartTrackMoonHandbookReward(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddGoal(FlatBufferBuilder builder, int goal) { builder.AddInt(1, goal, 0); }
  public static void AddRewardInfo(FlatBufferBuilder builder, int rewardInfo) { builder.AddInt(2, rewardInfo, 0); }
  public static Offset<WWParser.Defs.TrackMoonHandbookReward> EndTrackMoonHandbookReward(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.TrackMoonHandbookReward>(o);
  }
  public TrackMoonHandbookRewardT UnPack() {
    var _o = new TrackMoonHandbookRewardT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TrackMoonHandbookRewardT _o) {
    _o.Id = this.Id;
    _o.Goal = this.Goal;
    _o.RewardInfo = this.RewardInfo;
  }
  public static Offset<WWParser.Defs.TrackMoonHandbookReward> Pack(FlatBufferBuilder builder, TrackMoonHandbookRewardT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.TrackMoonHandbookReward>);
    return CreateTrackMoonHandbookReward(
      builder,
      _o.Id,
      _o.Goal,
      _o.RewardInfo);
  }
}

public class TrackMoonHandbookRewardT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("goal")]
  public int Goal { get; set; }
  [Newtonsoft.Json.JsonProperty("reward_info")]
  public int RewardInfo { get; set; }

  public TrackMoonHandbookRewardT() {
    this.Id = 0;
    this.Goal = 0;
    this.RewardInfo = 0;
  }
}


static public class TrackMoonHandbookRewardVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Goal*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*RewardInfo*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
