// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TrackMoonTargetType : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static TrackMoonTargetType GetRootAsTrackMoonTargetType(ByteBuffer _bb) { return GetRootAsTrackMoonTargetType(_bb, new TrackMoonTargetType()); }
  public static TrackMoonTargetType GetRootAsTrackMoonTargetType(ByteBuffer _bb, TrackMoonTargetType obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TrackMoonTargetType __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<WWParser.Defs.TrackMoonTargetType> CreateTrackMoonTargetType(FlatBufferBuilder builder,
      int id = 0,
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartTable(2);
    TrackMoonTargetType.AddName(builder, nameOffset);
    TrackMoonTargetType.AddId(builder, id);
    return TrackMoonTargetType.EndTrackMoonTargetType(builder);
  }

  public static void StartTrackMoonTargetType(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static Offset<WWParser.Defs.TrackMoonTargetType> EndTrackMoonTargetType(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.TrackMoonTargetType>(o);
  }
  public TrackMoonTargetTypeT UnPack() {
    var _o = new TrackMoonTargetTypeT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TrackMoonTargetTypeT _o) {
    _o.Id = this.Id;
    _o.Name = this.Name;
  }
  public static Offset<WWParser.Defs.TrackMoonTargetType> Pack(FlatBufferBuilder builder, TrackMoonTargetTypeT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.TrackMoonTargetType>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    return CreateTrackMoonTargetType(
      builder,
      _o.Id,
      _name);
  }
}

public class TrackMoonTargetTypeT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("name")]
  public string Name { get; set; }

  public TrackMoonTargetTypeT() {
    this.Id = 0;
    this.Name = null;
  }
}


static public class TrackMoonTargetTypeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
