// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WWParser.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct WeaponBreach : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static WeaponBreach GetRootAsWeaponBreach(ByteBuffer _bb) { return GetRootAsWeaponBreach(_bb, new WeaponBreach()); }
  public static WeaponBreach GetRootAsWeaponBreach(ByteBuffer _bb, WeaponBreach obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public WeaponBreach __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int BreachId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Level { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int ConditionId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int LevelLimit { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public WWParser.Defs.DicIntInt? Consume(int j) { int o = __p.__offset(14); return o != 0 ? (WWParser.Defs.DicIntInt?)(new WWParser.Defs.DicIntInt()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ConsumeLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  public int GoldConsume { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<WWParser.Defs.WeaponBreach> CreateWeaponBreach(FlatBufferBuilder builder,
      int id = 0,
      int breach_id = 0,
      int level = 0,
      int condition_id = 0,
      int level_limit = 0,
      VectorOffset consumeOffset = default(VectorOffset),
      int gold_consume = 0) {
    builder.StartTable(7);
    WeaponBreach.AddGoldConsume(builder, gold_consume);
    WeaponBreach.AddConsume(builder, consumeOffset);
    WeaponBreach.AddLevelLimit(builder, level_limit);
    WeaponBreach.AddConditionId(builder, condition_id);
    WeaponBreach.AddLevel(builder, level);
    WeaponBreach.AddBreachId(builder, breach_id);
    WeaponBreach.AddId(builder, id);
    return WeaponBreach.EndWeaponBreach(builder);
  }

  public static void StartWeaponBreach(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddBreachId(FlatBufferBuilder builder, int breachId) { builder.AddInt(1, breachId, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(2, level, 0); }
  public static void AddConditionId(FlatBufferBuilder builder, int conditionId) { builder.AddInt(3, conditionId, 0); }
  public static void AddLevelLimit(FlatBufferBuilder builder, int levelLimit) { builder.AddInt(4, levelLimit, 0); }
  public static void AddConsume(FlatBufferBuilder builder, VectorOffset consumeOffset) { builder.AddOffset(5, consumeOffset.Value, 0); }
  public static VectorOffset CreateConsumeVector(FlatBufferBuilder builder, Offset<WWParser.Defs.DicIntInt>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateConsumeVectorBlock(FlatBufferBuilder builder, Offset<WWParser.Defs.DicIntInt>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateConsumeVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<WWParser.Defs.DicIntInt>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateConsumeVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<WWParser.Defs.DicIntInt>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartConsumeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddGoldConsume(FlatBufferBuilder builder, int goldConsume) { builder.AddInt(6, goldConsume, 0); }
  public static Offset<WWParser.Defs.WeaponBreach> EndWeaponBreach(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WWParser.Defs.WeaponBreach>(o);
  }
  public WeaponBreachT UnPack() {
    var _o = new WeaponBreachT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(WeaponBreachT _o) {
    _o.Id = this.Id;
    _o.BreachId = this.BreachId;
    _o.Level = this.Level;
    _o.ConditionId = this.ConditionId;
    _o.LevelLimit = this.LevelLimit;
    _o.Consume = new List<WWParser.Defs.DicIntIntT>();
    for (var _j = 0; _j < this.ConsumeLength; ++_j) {_o.Consume.Add(this.Consume(_j).HasValue ? this.Consume(_j).Value.UnPack() : null);}
    _o.GoldConsume = this.GoldConsume;
  }
  public static Offset<WWParser.Defs.WeaponBreach> Pack(FlatBufferBuilder builder, WeaponBreachT _o) {
    if (_o == null) return default(Offset<WWParser.Defs.WeaponBreach>);
    var _consume = default(VectorOffset);
    if (_o.Consume != null) {
      var __consume = new Offset<WWParser.Defs.DicIntInt>[_o.Consume.Count];
      for (var _j = 0; _j < __consume.Length; ++_j) { __consume[_j] = WWParser.Defs.DicIntInt.Pack(builder, _o.Consume[_j]); }
      _consume = CreateConsumeVector(builder, __consume);
    }
    return CreateWeaponBreach(
      builder,
      _o.Id,
      _o.BreachId,
      _o.Level,
      _o.ConditionId,
      _o.LevelLimit,
      _consume,
      _o.GoldConsume);
  }
}

public class WeaponBreachT
{
  [Newtonsoft.Json.JsonProperty("id")]
  public int Id { get; set; }
  [Newtonsoft.Json.JsonProperty("breach_id")]
  public int BreachId { get; set; }
  [Newtonsoft.Json.JsonProperty("level")]
  public int Level { get; set; }
  [Newtonsoft.Json.JsonProperty("condition_id")]
  public int ConditionId { get; set; }
  [Newtonsoft.Json.JsonProperty("level_limit")]
  public int LevelLimit { get; set; }
  [Newtonsoft.Json.JsonProperty("consume")]
  public List<WWParser.Defs.DicIntIntT> Consume { get; set; }
  [Newtonsoft.Json.JsonProperty("gold_consume")]
  public int GoldConsume { get; set; }

  public WeaponBreachT() {
    this.Id = 0;
    this.BreachId = 0;
    this.Level = 0;
    this.ConditionId = 0;
    this.LevelLimit = 0;
    this.Consume = null;
    this.GoldConsume = 0;
  }
}


static public class WeaponBreachVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*BreachId*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Level*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*ConditionId*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*LevelLimit*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 14 /*Consume*/, WWParser.Defs.DicIntIntVerify.Verify, false)
      && verifier.VerifyField(tablePos, 16 /*GoldConsume*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
